language: python
python:
  - "2.7"
os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test 
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential zlib1g-dev ccache cmake libstdc++6
script: oss_local_scripts/make_egg.sh
